"use client";

import React, { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Copy, Check } from "lucide-react";
import dynamic from "next/dynamic";

const GalaxyCanvas = dynamic(
  () => import("@/components/particles/GalaxyCanvas").then((m) => m.GalaxyCanvas),
  { ssr: false }
);
const MouseTrailCanvas = dynamic(
  () => import("@/components/particles/MouseTrailCanvas").then((m) => m.MouseTrailCanvas),
  { ssr: false }
);
const ExplosionCanvas = dynamic(
  () => import("@/components/particles/ExplosionCanvas").then((m) => m.ExplosionCanvas),
  { ssr: false }
);
const WaveCanvas = dynamic(
  () => import("@/components/particles/WaveCanvas").then((m) => m.WaveCanvas),
  { ssr: false }
);
const NoiseFieldCanvas = dynamic(
  () => import("@/components/particles/NoiseFieldCanvas").then((m) => m.NoiseFieldCanvas),
  { ssr: false }
);

const DEMOS = [
  {
    id: "galaxy",
    title: "Galaxy Spiral",
    description:
      "A mathematical simulation of a spiral galaxy using log-polar coordinates. Three arms of stars rotate at different angular velocities with core glow.",
    tag: "WebGL Math",
    code: `// Spiral galaxy with 3 arms
const ARMS = 3;
const STARS_PER_ARM = 600;

stars = Array.from({ length: ARMS * STARS_PER_ARM }, (_, i) => {
  const arm = i % ARMS;
  const t = (i / STARS_PER_ARM) * Math.PI * 4;
  const r = (t / (Math.PI * 4)) * 0.4 + 0.02;
  const offset = (arm / ARMS) * Math.PI * 2;
  return { angle: t + offset, r, speed: 0.0002 };
});

// Render loop
useFrame(() => {
  stars.forEach(s => {
    s.angle += s.speed;
    const x = cx + Math.cos(s.angle) * s.r * scale;
    const y = cy + Math.sin(s.angle) * s.r * scale * 0.5;
    ctx.arc(x, y, s.size, 0, Math.PI * 2);
  });
});`,
    canvas: <GalaxyCanvas />,
  },
  {
    id: "trail",
    title: "Mouse Trail",
    description:
      "Chromatic burst particles that spawn at cursor position with velocity, gravity, and fade-out. Hue rotates continuously for rainbow trails.",
    tag: "Cursor Reactive",
    code: `// Spawn 6 particles per mouse move
canvas.addEventListener("mousemove", (e) => {
  hue = (hue + 1) % 360;
  for (let i = 0; i < 6; i++) {
    particles.push({
      x: e.clientX, y: e.clientY,
      vx: (Math.random() - 0.5) * 3,
      vy: (Math.random() - 0.5) * 3 - 1,
      life: 1,
      hue,
      size: Math.random() * 6 + 2,
    });
  }
});

// Physics update each frame
particles.forEach(p => {
  p.x += p.vx;
  p.y += p.vy;
  p.vy += 0.05; // gravity
  p.life *= 0.94; // fade
});`,
    canvas: <MouseTrailCanvas />,
  },
  {
    id: "explosion",
    title: "Explosion Effect",
    description:
      "Physics-based particle burst system with gravity, velocity decay, and radial spawn patterns. Click anywhere on the canvas to trigger explosions.",
    tag: "Interactive",
    code: `function explode(cx, cy) {
  const count = 80 + Math.floor(Math.random() * 60);
  const baseHue = Math.random() * 360;

  for (let i = 0; i < count; i++) {
    const angle = (i / count) * Math.PI * 2;
    const speed = Math.random() * 8 + 2;
    particles.push({
      x: cx, y: cy,
      vx: Math.cos(angle) * speed,
      vy: Math.sin(angle) * speed,
      life: 1,
      hue: baseHue + Math.random() * 60,
    });
  }
}

// Gravity on each particle
p.vy += 0.12;
p.life -= 0.018;`,
    canvas: <ExplosionCanvas />,
  },
  {
    id: "wave",
    title: "Wave Particles",
    description:
      "Sinusoidal wave system where each particle oscillates at its own amplitude, speed, and phase offset. Creates mesmerizing multi-frequency wave patterns.",
    tag: "Trigonometry",
    code: `const particles = Array.from({ length: 120 }, (_, i) => ({
  x: (i / 120) * canvas.width,
  baseY: canvas.height / 2,
  amp: Math.random() * 60 + 20,    // amplitude
  speed: Math.random() * 0.02 + 0.01,
  phase: (i / 120) * Math.PI * 2, // phase offset
  hue: 160 + (i / 120) * 100,
}));

// Each frame
particles.forEach(p => {
  const y = p.baseY + Math.sin(t * p.speed + p.phase) * p.amp;
  ctx.arc(p.x, y, p.size, 0, Math.PI * 2);
});`,
    canvas: <WaveCanvas />,
  },
  {
    id: "noise",
    title: "Noise Field",
    description:
      "Autonomous agents that follow a 2D vector field generated by layered sine/cosine noise. The field evolves over time creating organic flow patterns.",
    tag: "Flow Field",
    code: `// Pseudo-noise from trig layers
function noise(x, y, t) {
  return (
    Math.sin(x * 0.01 + t) * Math.cos(y * 0.008 + t * 0.7) +
    Math.sin((x + y) * 0.005 + t * 1.3) * 0.5
  );
}

// Agent follows field direction
agents.forEach(a => {
  const angle = noise(a.x * w, a.y * h, t) * Math.PI * 4;
  a.x += Math.cos(angle) * 0.003;
  a.y += Math.sin(angle) * 0.003;
  // Wrap at edges
  if (a.x > 1) a.x = 0;
  if (a.y > 1) a.y = 0;
});`,
    canvas: <NoiseFieldCanvas />,
  },
];

function CodeBlock({ code }: { code: string }) {
  const [copied, setCopied] = useState(false);
  return (
    <div className="relative h-full">
      <button
        onClick={() => {
          navigator.clipboard.writeText(code);
          setCopied(true);
          setTimeout(() => setCopied(false), 2000);
        }}
        className="absolute top-3 right-3 z-10 flex items-center gap-1.5 text-[10px] glass px-2 py-1 rounded-md text-white/40 hover:text-primary transition-colors"
      >
        {copied ? <Check size={10} /> : <Copy size={10} />}
        {copied ? "Copied" : "Copy"}
      </button>
      <pre className="text-[11px] font-mono text-white/70 overflow-auto h-full p-5 leading-relaxed">
        <code>{code}</code>
      </pre>
    </div>
  );
}

export default function ParticlesPage() {
  const [active, setActive] = useState(DEMOS[0].id);
  const demo = DEMOS.find((d) => d.id === active)!;

  return (
    <div className="pt-28 min-h-screen flex flex-col">
      {/* Header */}
      <div className="px-6 max-w-7xl mx-auto w-full py-10">
        <motion.h1
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="text-5xl md:text-7xl font-black tracking-tighter mb-4 uppercase"
        >
          Particles
        </motion.h1>
        <motion.p
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.2 }}
          className="text-xl text-white/50 max-w-xl"
        >
          Live particle systems running in your browser. Click a demo — then interact with the canvas.
        </motion.p>
      </div>

      {/* Tab Nav */}
      <div className="border-y border-white/10 px-6">
        <div className="max-w-7xl mx-auto flex gap-1 overflow-x-auto py-3 scrollbar-hide">
          {DEMOS.map((d) => (
            <button
              key={d.id}
              onClick={() => setActive(d.id)}
              className={`px-5 py-2 rounded-full text-sm font-medium whitespace-nowrap transition-all ${
                active === d.id
                  ? "bg-primary text-black font-bold"
                  : "text-white/50 hover:text-white hover:bg-white/5"
              }`}
            >
              {d.title}
            </button>
          ))}
        </div>
      </div>

      {/* Main Demo Area */}
      <AnimatePresence mode="wait">
        <motion.div
          key={active}
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          transition={{ duration: 0.3 }}
          className="flex-1 grid grid-cols-1 lg:grid-cols-[1fr_420px]"
        >
          {/* Canvas */}
          <div className="relative min-h-[380px] lg:min-h-0">{demo.canvas}</div>

          {/* Info Panel */}
          <div className="glass-dark border-l border-white/10 flex flex-col overflow-hidden">
            <div className="p-8 border-b border-white/10 flex-shrink-0">
              <span className="text-[10px] uppercase tracking-widest font-bold text-primary mb-3 block">
                {demo.tag}
              </span>
              <h2 className="text-2xl font-bold mb-3">{demo.title}</h2>
              <p className="text-white/60 text-sm leading-relaxed">{demo.description}</p>
            </div>

            <div className="flex-1 overflow-hidden">
              <div className="px-6 py-3 border-b border-white/10">
                <span className="text-[10px] uppercase tracking-widest text-white/30 font-bold">
                  Source Code
                </span>
              </div>
              <CodeBlock code={demo.code} />
            </div>
          </div>
        </motion.div>
      </AnimatePresence>
    </div>
  );
}
